### ISSUE TITLE
MVC 5.2.30: Model binding error in Razor

### ISSUE THREAD

**Issue by argimenes** [aspnet/AspNetWebStack#137] opened 2018-03-08 00:26 UTC
When attempting to bind the value of Model.Title in Html.TextBox() while using HttpUtility.HtmlDecode(Model.Title), the value of ViewBag.Title gets bound instead when the value of Model.Title is null.

`@Html.TextBox("Title", HttpUtility.HtmlDecode(Model.Title), new { @class = "form-control" })`

**Comment by dougbu** [comment] 2018-04-03 22:03
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design. The `string`-based HTML helpers fall back to `ViewData` / `ViewBag` and `ModelState` when the named expression value is `null`.

**Closed by dougbu** 2018-04-03 22:03 UTC
