### ISSUE TITLE
Handling 500 errors in WebAPI

### ISSUE THREAD

**Issue by nanosanu** [aspnet/AspNetWebStack#106] opened 2017-11-23 17:13 UTC
We are seeing 500 errors being thrown from ASP.NET 4.6 Web API based application and want to handle it more gracefully (may be give a proper error message to the end user). With data like dumps collected it appears like this may be due to some network issues but in Cloud env this may be expected for such network glitches. We are not able to catch these exceptions in try catch blocks. Although exceptions don't bubble out of WebApi, and get converted to plain 500, this may not be useful. We tried IExceptionFilter / ExceptionFilterAttribute as per https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling (exception thrown during response content serialization) as below but still it fails. Request on inputs on how we can handle this.

internal class GlobalExceptionHandler : ExceptionHandler
    {
        #region Public Methods and Operators

        public override void Handle(ExceptionHandlerContext context)
        {
            var response = new HttpResponseMessage();

            var exception = context.Exception;

            if (exception is AggregateException aggregateException &&
                aggregateException.InnerExceptions.Count == 1)
            {
                exception = aggregateException.InnerException;
            }

            switch (exception)
            {
                case NebulaWebException nebulaWebException:
                    response.StatusCode = nebulaWebException.HttpStatusCode;
                    response.Content = new StringContent(nebulaWebException.Error?.ToErrorJson(), Encoding.UTF8, "application/json");
                    break;
                case HttpException _ when context.Exception.Message.EqualsIgnoreCase("The client disconnected."):
                    response.StatusCode = HttpStatusCode.BadRequest;
                    response.Content = new StringContent(context.Exception.Message);
                    break;
                default:
                    response.StatusCode = HttpStatusCode.InternalServerError;
                    break;
            }

            context.Result = new ResponseMessageResult(response);
        }

        #endregion
    }

public class SystemExceptionLogger : ExceptionLogger
    {
        #region Public Methods and Operators

        public override void Log(ExceptionLoggerContext context)
        {
            try
            {
                HttpContext.Current.Items[ContextSlotName.Exception] = context.Exception.ToString();
            }
            catch (Exception ex)
            {
                Logger.Error(ex.ToString());
            }

            LogException(context.Exception);
        }

        #endregion

        #region Methods

        private static void LogException(Exception exception)
        {
            if (exception is NebulaWebException)
            {
                Logger.Warn(exception.ToString());
            }
            else
            {
                Logger.Error(exception.ToString());
            }
        }

        #endregion
    }

**Comment by dougbu** [comment] 2017-12-07 17:20
@nanosanu have you debugged the application to confirm an `Exception` is thrown?

**Comment by nanosanu** [comment] 2017-12-19 11:24
Most of times these exceptions are occuring in prod env where debugging is not much of an option as I guess this is happening due to network related issues. I did try collecting an iDNA but it turned out to be corrupt. Will try to add users who were able to repro this

**Comment by MSRY** [comment] 2017-12-19 18:27
I can reproduce this by following steps.
First, create a web API to handle scenarios like file upload, you can read stream content from the client request.
Second create an application to continue call web API to upload file.
Third, Create a test case to use process to start the application created in second step and kill that process at random time.
Now you will see the exception on web API cannot be caught.

**Comment by MSRY** [comment] 2017-12-19 18:30
By the way the detail exception in FREB in this reproduce is different from what we have in our production which I think in production it is caused by stream reading in another thread, but the common part of these two is the exception occurred in content transportation will be lost sometimes.

**Comment by mkArtakMSFT** [comment] 2017-12-29 17:11
@MSRY, can you please share a project which we can use to repro the issue?

**Comment by dougbu** [comment] 2018-04-03 22:01
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-04-03 22:01 UTC
Labels: investigate

**Comment by MSRY** [comment] 2018-04-03 22:08
Hi,

I have already provided the repro steps.

Thanks
Ren

**Comment by dougbu** [comment] 2018-04-03 22:39
@MSRY the following part of your repro steps is not clear:
> you will see the exception on web API cannot be caught

A small project or set of projects (preferably in a GitHub repo) would be ideal.
