### ISSUE TITLE
PostAsJsonAsync extension method sets Content-Length to 0 in .NET Core 2.1 with any versions of System.Net.Http and System.Net.Http.Formatting

### ISSUE THREAD

**Issue by doboczyakos** [aspnet/AspNetWebStack#252] opened 2019-07-22 08:52 UTC
``` c#
var response = await _client.PostAsJsonAsync(requestUri, value, cancellationToken);
```

Request object is null on the server side because content length is set to 0.
I've tried the newest versions of System.Net.Http and System.Net.Http.Formatting and the issue is the same.
It works if I replace this with the following:
``` c#
var objectContent = new ObjectContent(value, new System.Net.Http.Formatting.JsonMediaTypeFormatter(), (System.Net.Http.Headers.MediaTypeHeaderValue)null);
await objectContent.ReadAsStringAsync();
var response = await _client.PostAsync(requestUri, objectContent, cancellationToken);
```

**Comment by dougbu** [comment] 2019-07-22 17:48
Adding @mkArtakMSFT and @danroth27 

@doboczyakos have you debugged the server application to confirm the `Content-Length` header is present in the request and that `Transfer-Encoding` is not? And, is there a proxy between your client and server (proxies sometimes mess with `Content-Length`)?

(I edited your description to make the code a bit easier to read.)

**Comment by doboczyakos** [comment] 2019-07-22 19:10
The server application is an ASP.NET web api application on local IIS. I saw that content length was 0 but I'm double checking it tomorrow.
The above mentioned code is in a .NET standard 2.0 class library and the executed client application is .NET Core 2.1

**Comment by doboczyakos** [comment] 2019-07-23 15:42
Transfer-Encoding: chunked and no Content-Length header

**Comment by doboczyakos** [comment] 2019-07-23 15:58
It also works if I run this from a .NET Framework 4.8 application

**Comment by dougbu** [comment] 2019-07-23 16:01
This sounds like a duplicate of #197 and that was fixed in the 5.2.7 release. Are you using the latest packages in the web app?

**Comment by doboczyakos** [comment] 2019-07-23 16:05
You mean on the server side?

**Comment by doboczyakos** [comment] 2019-07-23 16:09
...just because the client side is a .NET Core 2.1 Console Application.
I already tried Microsoft.AspNet.WebApi.Client 5.2.7 but I've just double-checked it with no success.
It also works on an other machine which has .NET Core 3 Preview installed.

**Comment by doboczyakos** [comment] 2019-07-23 16:20
Ok. I've read the linked thread. What happens if I can make no effect on the server side?

**Comment by dougbu** [comment] 2019-07-23 16:26
I meant the server side. The client sending `Transfer-Encoding` without `Content-Length` is correct according to the HTTP 1.1 spec. But, the server interpreting a missing `Content-Length` as `0` when the request is chunked is not correct. That's what #197 fixed.

I'm having trouble following your changes to the client and server applications. You seem to be changing package versions in the client application as well as the target framework for at least the client app. When using the latest client and server Web.API package (no ASP.NET Core packages in the server app) and targeting .NET Core 3.0 in the client and .NET Framework 4.7.2 (say) in the server? Does the problem reproduce when you move the client to .NET Core 2.2 or 2.1?

**Comment by doboczyakos** [comment] 2019-07-23 16:33
The client is targeting .NET Core 2.1 (and tested with 2.2 too)
The server side is .NET Framework 4.8
I've made no changes on the server side.

**Comment by mkArtakMSFT** [comment] 2019-07-29 17:48
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by pranavkm** [comment] 2019-07-29 17:59
> Ok. I've read the linked thread. What happens if I can make no effect on the server side?

@doboczyakos unfortunately a fix on the server would be required. You could consider changing the client to buffer and send a `Content-Length` if the server cannot be modified. However, beyond that, I'm not sure there's much we could do here.

**Comment by doboczyakos** [comment] 2019-08-01 08:27
> @doboczyakos unfortunately a fix on the server would be required. You could consider changing the client to buffer and send a `Content-Length` if the server cannot be modified. However, beyond that, I'm not sure there's much we could do here.

I have the workaround which is quite funny but works. I'm wondering why the client can't have this as a feature especially when .NET Framework has this bug on server side. Please let me understand your way of thinking about it.

**Comment by pranavkm** [comment] 2019-08-13 18:12
@doboczyakos the bug was fixed on the server. We generally wouldn't accept a workaround for a bug fix that has a known patch.

**Comment by Rwing** [comment] 2019-08-30 00:53
I had the same problem now, and I used Fiddler to confirm the 'Content-Lenght' real not in request headers.

**Comment by mkArtakMSFT** [comment] 2019-09-16 23:32
Closing as there is no pending action here.

**Closed by mkArtakMSFT** 2019-09-16 23:32 UTC
Labels: more-info-needed

**Comment by gojanpaolo** [comment] 2020-02-08 23:46
Hello, we're also getting this issue. We could send a minimal reproducible example through a private message because a subscription key should be added to the headers.

But basically, server returns Bad Request when we use `PostAsJsonAsync`.
```c#
var response = await httpClient.PostAsJsonAsync(
    @"https://apidata.guidestar.org/essentials/v2",
    new { search_terms = "test" });
```

Everything works as expected when we use `PostAsync`.
```c#
var response = await httpClient.PostAsync(
    @"https://apidata.guidestar.org/essentials/v2",
    new StringContent(JsonConvert.SerializeObject(new { search_terms = "test" }))
    {
        Headers = { ContentType = new MediaTypeHeaderValue("application/json") }
    });
```

---

.NET Core 3.1
`Microsoft.AspNet.WebApi.Client` 5.2.7

**Comment by danroth27** [comment] 2020-02-10 19:22
@gojanpaolo `PostAsJsonAsync` sends a chunked encoded request. It sounds like the API you're trying to call doesn't support that. If you need to send a request with a set content length, then there isn't a way to do that with `PostAsJsonAsync` and you'll need to buffer the request yourself as you've done in your second example.

**Comment by gojanpaolo** [comment] 2020-02-10 19:36
@danroth27 I see. Is it possible for `PostAsJsonAsync` to support this in the future? Thanks!

**Comment by danroth27** [comment] 2020-02-10 21:27
We're actually working on some next extension methods for HttpClient based on System.Text.Json. Adding @terrajobst to capture this requirement.

**Comment by terrajobst** [comment] 2020-02-11 01:13
@danroth27 

Are you saying `PostAsJsonAsync` should also support sending non-chunked data to the server, as in in one big shot?

**Comment by gperrego** [comment] 2020-04-22 07:28
> oesn't support that. If you need to send a request with a set content length, then there isn't a way to do that with `PostAsJsonAsync` and you'll need to buffer the request yourself as you've done in your second example.

@danroth27 I'm seeing the same behavior in HttpClient.PostAsync, so should I follow the same path, do the buffering myself?

**Comment by gperrego** [comment] 2020-04-22 13:27
> @gojanpaolo `PostAsJsonAsync` sends a chunked encoded request. It sounds like the API you're trying to call doesn't support that. If you need to send a request with a set content length, then there isn't a way to do that with `PostAsJsonAsync` and you'll need to buffer the request yourself as you've done in your second example.

@danroth27 I'm seeing the similar behavior in the .net standard implementation of HttpClient.PostAsync.  When calling it from .net 472 the content length is in the header, when calling it from .net Core 2.1 it is using chunked.  

var callTask = Task.Run(() => HttpClient.PostAsync(
                PostUri, 
                request, 
                new JsonMediaTypeFormatter()));

1. Is there a way to use this shared code from both clients?  
2. If not I guess because we wrote the API also I could try to add chunked support to the API?  But then I'm not sure if doing so would cause the 472 framework call would fail?

I can open this as a new issue if needed?

Thanks,
Greg

**Comment by danroth27** [comment] 2020-04-22 18:01
@gperrego Probably best to open a new issue. It is strange that the behavior is different depending on whether you're running on .NET 4.7.2 vs .NET Core 2.1.
