### ISSUE TITLE
Is there a reason to generate code with Tuple.Create instead of the classes required by WriteAttribute()?

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#151] opened 2018-04-11 16:32 UTC
_From @JendaPerl on April 11, 2018 14:30_

Is there a reason the code generated from cshtml contains

`WriteAttribute("class", Tuple.Create(" class=\'", 743), Tuple.Create("\'", 812)
, Tuple.Create(Tuple.Create("", 751), Tuple.Create("ft-filter__whisper", 751), true)
, Tuple.Create(Tuple.Create(" ", 769), Tuple.Create<System.Object, System.Int32>(Model.Filters.IsEmpty() ? "" : "active", 770), false)
);`
instead of
`WriteAttribute("class", new System.Web.WebPages.Instrumentation.PositionTagged<string>(" class=\'", 743), new System.Web.WebPages.Instrumentation.PositionTagged<string>("\'", 812)
, new AttributeValue( new System.Web.WebPages.Instrumentation.PositionTagged<string>("", 751),  new System.Web.WebPages.Instrumentation.PositionTagged<object>("ft-filter__whisper", 751), true)
, new AttributeValue( new System.Web.WebPages.Instrumentation.PositionTagged<string>(" ", 769), new System.Web.WebPages.Instrumentation.PositionTagged<object>(Model.Filters.IsEmpty() ? "" : "active", 770), false)
);`

doubling the number of instances created in runtime? The Tuples get converted to the specific classes using implicit conversion operators so why not save CPU cycles and skip the Tuples altogether?

The long strings of WriteLiteral() calls with short string literals do not look particularly efficient either.

_Copied from original issue: aspnet/Razor#2255_

**Comment by Eilon** [comment] 2018-04-11 16:34
Tagging @NTaylorMullen and @jodavis in case either of them know more about the history of this.

Though, I'd also add that one way or another, unless this somehow causes a noticeable perf degradation, it's unlikely that this would be fixed. This instrumentation code is generated only during development, so some liberties are taken with regard to performance.

**Comment by JendaPerl** [comment] 2018-04-14 08:59
This code is generated once and executed very many times so it would make sense to work harder on the generation so that the resulting code is efficient. Anyway I ended up using RazorGenerator to pregenerate and compile the views and there is a way to instruct the tool to run the generated code through your transformations. So now I turn a row of WriteLiteral() calls into one, transform the first two parameters of WriteAttribute() to PositionTagged constructor calls and Write(Html.Raw( to WriteLiteral((. Together with adding more efficient overloads for Write(int value) and friends it does give me a 1% boost. It might not look like much, but it's a one time cost and it helps everywhere.

**Comment by dougbu** [comment] 2018-04-17 22:12
As @Eilon said, the code is generated this way only during development. It is not a production issue.

The background reason is debugging from the browser. With this in place, Visual Studio users should be able to see where they are in the .cshtml file while browsing the generated HTML.

In any case @JendaPerl, thank-you for your feedback. We're closing this issue as the behaviour discussed is by design.

**Closed by dougbu** 2018-04-17 22:12 UTC
Labels: question
