### ISSUE TITLE
Inject custom json serializer in JsonResult

### ISSUE THREAD

**Issue by gelambert** [aspnet/AspNetWebStack#216] opened 2018-12-06 13:03 UTC
It would be nice to give possibility to inject a custom json serializer in `JsonResult`.

I find the current one (`JavaScriptSerializer`) sometimes limited (for example when i want to camel case the properties of my object).

It would result in something like below :
```
if (Data != null)
{
    if (CustomSerializer != null) {
        response.Write(CustomSerializer(Data));
    } else { // Current code untouched
        JavaScriptSerializer serializer = new JavaScriptSerializer();
        if (MaxJsonLength.HasValue)
        {
            serializer.MaxJsonLength = MaxJsonLength.Value;
        }
        if (RecursionLimit.HasValue)
        {
            serializer.RecursionLimit = RecursionLimit.Value;
        }
        response.Write(serializer.Serialize(Data));
    }
}
```

Could this feature be considered ?
Currently, I am using a class which inherits from JsonResult to achieve what I want.

**Comment by dougbu** [comment] 2019-01-24 23:58
Thank you for your feedback. We do not plan to add additional extensibility to `JsonResult`.

Creating your own `ActionResult` is exactly what we recommend. (Not sure if deriving from `JsonResult` helps but that's up to you.) We're closing this issue as the behaviour discussed is by design.

**Closed by dougbu** 2019-01-24 23:58 UTC
