### ISSUE TITLE
RequestContext modifies the global settings, not just the current request.

### ISSUE THREAD

**Issue by chrisgalvan** [aspnet/AspNetWebStack#153] opened 2018-04-25 18:25 UTC
Running this line in a WebApi action will modify the global settings not the current request.
```csharp
actionContext.RequestContext.Configuration.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
```
*Setting ContractResolver inside RequestContext modifies the global settings*  
Setting ContractResolver inside RequestContext modifies global settings, not just the current request settings.

### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
I would like to apply changes to specific actions (per request) not to all the calls.

### Minimal repro steps
*Repro steps*  
 - Have this WebAPI controller.
```csharp
using Newtonsoft.Json.Serialization;
using System.Net.Http;
using System.Web.Http;

namespace WebApiContractResolverIssue.Controllers
{
    [RoutePrefix("api/serializer")]
    public class SerializerController : ApiController
    {
        [HttpGet]
        [Route("first")]
        public HttpResponseMessage First()
        {
            var obj = new
            {
                Id = 1,
                Name = "CamelCase"
            };

            this.RequestContext.Configuration.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            return Request.CreateResponse(obj);
        }

        [HttpGet]
        [Route("second")]
        public HttpResponseMessage Second()
        {
            var obj = new
            {
                Id = 1,
                Name = "PascalCase"
            };

            return Request.CreateResponse(obj);
        }
    }
}
```

### Expected result
*What would you expect to happen if there wasn't a bug*  
- Calling first endpoint should return camel case `http://localhost:54714/api/serializer/first`
*response*
```json
{
  "id":1,
  "name":"CamelCase"
}
```
- Calling second endpoint should return pascal case (default) `http://localhost:54714/api/serializer/second`
*response*
```json
{
  "Id":1,
  "Name":"PascalCase"}
```

### Actual result
*What is actually happening*  
- Calling first endpoint returns camel case `http://localhost:54714/api/serializer/first`
*response*
```
{
  "id":1,
  "name":"CamelCase"
}
```
-  Calling second endpoint returns camel case `http://localhost:54714/api/serializer/second`
*response*
```
{
  "id":1,
  "name":"PascalCase"
}
```

### Additional notes:
We have a big project already using default serialization (pascal) and we want to migrate some (not all controller/actions) to use camel case.

Hitting the second endpoint first, returns properly (pascal case) just whenever you hit the first endpoint it changes the `default` behavior for all future requests.

Using 
WebAPI 2
.NetFramework 4.7.1
Microsoft.AspNet.WebApi version=5.2.3 targetFramework=net45

**Comment by dougbu** [comment] 2018-05-03 23:13
Thank you for your feedback.

`RequestContext.Configuration` _is_ the global configuration and it is intended only for reading in the context where you're writing to it. So with respect to the title of this issue, we're closing this issue as the behaviour discussed is by design.

On the other hand, your scenario is supported. Implement an `IControllerConfiguration` attribute to adjust the formatters as you prefer e.g. replace the `JsonMediaTypeFormatter` in the list with another instance where you've changed the formatter's `SerializerSettings`. See https://blogs.msdn.microsoft.com/jmstall/2012/05/11/per-controller-configuration-in-webapi/ for a bit more information about `IControllerConfiguration` implementations.

**Closed by dougbu** 2018-05-03 23:13 UTC

**Comment by chrisgalvan** [comment] 2018-05-04 02:00
I don't think the link you provided cover my scenario. My scenario is: same controller different formatter per action; the link provided is a way to override global settings at the controller level, but all the actions in the same controller will be affected. Am I missing anything?

**Comment by dougbu** [comment] 2018-05-04 05:35
Split your controller in two. Use attribute routing if it's necessary for the two controllers to share a common prefix.
