### ISSUE TITLE
Update intellisense Error

### ISSUE THREAD

**Issue by ekremdnkc** [aspnet/AspNetWebStack#132] opened 2018-02-19 00:02 UTC
![old](https://user-images.githubusercontent.com/36610938/36358519-ebcbe110-1520-11e8-82d7-d6b6e4eb0dae.PNG)
![old1](https://user-images.githubusercontent.com/36610938/36358523-f03f2edc-1520-11e8-90fa-093489f15afe.PNG)
![new](https://user-images.githubusercontent.com/36610938/36358526-f2d460cc-1520-11e8-82e5-fcb5be30cd32.PNG)
the error disappeared as shown in the pictures after updating.

I also want to use @ html.partial ("") when intellisense does not work.

I am sorry for my English

**Comment by dougbu** [comment] 2018-02-20 23:01
Thank you for contacting us.

To evaluate this issue, we'd like to understand more about the problem. Could you please elaborate on the scenario and the issue you are seeing? Or, could you please provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

In particular, we see you have upgraded from MVC 5.2.3 to 5.2.4 but do not know whether that is where the problem lies. What error is visible? What do you expect instead of that error? Or, is it an issue that the error goes away with the newer MVC packages?

**Comment by dougbu** [comment] 2018-04-03 22:01
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-04-03 22:01 UTC
