### ISSUE TITLE
Duplication of data reading FormDataCollection as NameValueCollection

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetWebStack#115] opened 2017-12-16 21:58 UTC
I have an external service that POSTs emails to a WebApi endpoint as form data. Since the fields can change, I am trying to receive the POST body as a `FormDataCollection`. When I call the `ReadAsNameValueCollection` method, the results are inconsistent with the POSTed data.

For example, the beginning of the raw form data looks like this:

`recipient=test%40example.com&sender=user%40gmail.com&subject=subject&from=UserName+%3Cuser%40gmail.com%3E`

After some URL decoding the values *should* be:

    recipient = test@example.com
    sender = user@gmail.com
    subject = subject
    from = UserName <user@gmail.com>

But when I convert to a `NameValueCollection` and iterate over the keys and values, a couple of the values are returned as two copies of the data separated by a comma:

    subject = subject,subject
    from = UserName <user@gmail.com>,UserName <user@gmail.com>

There are 26 fields in my test emails (it would vary if there were attachments, for example), and this problem only affects the `subject` and `from` fields, as shown above -- both of which are just plain text, nothing special about them.

The MVC stack (including `System.Net.Http.Formatting` where `FormDataCollection` lives) are all versioned at 5.2.3. This is deployed to a .NET Framework 4.7 Azure app service website.

**Comment by MV10** [comment] 2017-12-17 13:59
On stackoverflow somebody asked for the code. It really is this simple (I trimmed it down to bare-bones debug code after some email address validation blew up on known-good test data -- unfortunately the service sending the test emails doesn't like the SSL picture when I change things around to allow attaching the VS debugger). BlobWriter is just a little helper class I wrote to dump a string to storage.

I should also note, requesting a specific key/value from the `FormDataCollection` (rather than dumping them iteratively) confirms the incorrect content. For example, `postBody.Get("subject")` yields `subject,subject` as the stored value.

    public async Task<IHttpActionResult> ReceiveEmail(FormDataCollection postBody)
    {
        NameValueCollection email = postBody.ReadAsNameValueCollection();

        // Debug: dump key/vals
        StringBuilder sb = new StringBuilder();
        foreach(string key in email.AllKeys) sb.AppendLine($"{key} == {email[key]}");
        await BlobWriter.Write("debug-container", "email.txt", sb.ToString());

        return Ok();
    }

**Comment by mkArtakMSFT** [comment] 2017-12-27 19:05
@dougbu, can you please have a look at this?

**Comment by dougbu** [comment] 2018-02-08 21:58
I'm unable to reproduce this problem. My test app includes an antiforgery token from the test MVC view that submits the values. But, the other values submitted and the Form URL encoding are identical to the description above. I'm also using Web API 3.2.3 (package version 5.2.3) and .NET Framework 4.7.1.

Please provide more information to help us understand when this issue occurs.

**Comment by dougbu** [comment] 2018-02-08 21:58
Temporarily clearing the `investigate` label.

**Comment by dougbu** [comment] 2018-02-18 02:41
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-02-18 02:41 UTC
