### ISSUE TITLE
Fix null ref in DefaultControllerFactory

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#6] opened 2016-07-23 22:45 UTC
See original code in https://aspnetwebstack.codeplex.com/SourceControl/network/forks/Therzok/fixNRERegression/contribution/5358

```
<! RouteData routeData = requestContext.RouteData;   
!> RouteData routeData = requestContext != null ? requestContext.RouteData : null;  
```

**Comment by dougbu** [comment] 2017-10-08 20:22
NRE fixed in the [original PR](https://aspnetwebstack.codeplex.com/SourceControl/network/forks/Therzok/fixNRERegression/contribution/5358) is no longer an issue because the method (`GetControllerType(...)`) now throws an `ArgumentNullException` [a few lines earlier](https://github.com/aspnet/AspNetWebStack/blob/da59ce7f2aa180515aee1e2650828a148899465d/src/System.Web.Mvc/DefaultControllerFactory.cs#L197-L200) when `requestContext == null`.

On the other hand, `DefaultControllerFactory` lacks a `null` check for the `RequestContext` parameter in `GetControllerInstance(...)` and `CreateController(...)` and `GetControllerType(...)` both mishandle `requestContext.RouteData`. I'll send out a PR to address those small issues.

**Comment by dougbu** [comment] 2017-10-17 22:52
34827991

**Closed by dougbu** 2017-10-17 22:52 UTC
Labels: 2 - Working, bug
