### ISSUE TITLE
MapToApiVersion does not work anymore

### ISSUE THREAD

**Issue by angelacalborean** [aspnet/AspNetWebStack#227] opened 2019-02-01 15:05 UTC
Before, we were using 5.2.3 and had this code:
A FileController

```
[ApiVersion("1")]
[RoutePrefix("api/v{version:apiVersion}/file")]
public class FileController : BaseController
{
    [HttpPost]
    [MapToApiVersion("1")]
    [Route("uploadmethod"), Obsolete("The action is marked as obsolete for missing the support for userId. Please use uploadmethod from version 2.")]
    public async Task<HttpResponseMessage> UploadFileStream([FromUri] string filePath = null...)
    {

    }
}
```

And then another controller that derives from the one above:

```
[ApiVersion("2")]
[RoutePrefix("api/v{version:apiVersion}/file")]
public class FileController : Controllers.FileController
{
    [HttpPost]
    [MapToApiVersion("2")]
    [Route("uploadmethod")]
    public async Task<HttpResponseMessage> UploadFileWithUserId([FromUri] string userId = null, [FromUri] string filePath = null)
    {
       //at some point here I call an internal method from the base FileController
    }
}
```
When using, 5.2.3, the following requests were working fine, with the correct routing.
`$"api/v1/file/uploadmethod?filePath={path}";`

If I keep the code as it is, I get this error, when I want to make a request to v1 version of the api
**"Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL."**

I need the MapToApiVersion attribute because I need to test below to succeed: all calls to v2, without having a usedId specified should fail:

```
    [Fact]
    public async Task UploadFileUsingVersion2NUserId_WillThrowError_MethodsIsMissingOnThatVersion()
    {       
            //...
            var url = $"api/v2/file/uploadmethod?filePath={path}";

            // When
            var response = await api.UploadFile(url, content);

            // Then
            Assert.Equal(HttpStatusCode.MethodNotAllowed, response.StatusCode);
            var errorResponse = await response.Content.ReadAsJsonAsync<UnsupportedVersionResponse>();
            Assert.Equal("UnsupportedApiVersion", errorResponse.Error.Code);
    }
```

**Comment by commonsensesoftware** [comment] 2019-02-06 00:44
Hi @angelacalborean. In the future, it's best to ask [API Versioning](https://github.com/Microsoft/aspnet-api-versioning/issues) specific questions on that repo, but let's see if we can't get you sorted out.

At first glance, I would just expect this to work. I tried your repro and it indeed worked. BTW, thanks for that, it saves a lot of time (++ for having tests too!). Since you are trying to use inheritance, this leads me to only one conclusion - you've swapped out the implementation of the default **IDirectRouteProvider**. _Direct Routing_ (aka _attribute routing_) does **not** intrinsically support inheritance. You have likely changed that behavior. The API version attributes are not inherited either. This is by design; otherwise, the list of API versions per controller would keep growing for each subclass.

So what does this mean? Here's what the Web API routing system is seeing:

```c#
[ApiVersion( "2" )]
[RoutePrefix( "api/v{version:apiVersion}/file" )]
public class FileController : Controllers.FileController
{
  // NOTE: this is how the method looks to Web API through inheritance
  // MapToApiVersion is NOT inherited so it implicitly becomes 2.0
  [HttpPost]
  [Route( "uploadmethod" )] // the attribute is inherited, but you had to 'make' it supported
  public HttpResponseMessage UploadFileStream( [FromUri] string filePath = null ) => Ok();

  // this is now a duplicate route entry because it also maps to 2.0
  [HttpPost]
  [MapToApiVersion( "2" )]
  [Route( "uploadmethod" )]
  public HttpResponseMessage UploadFileWithUserId(
    [FromUri] string userId = null,
    [FromUri] string filePath = null ) => Ok();
}
```

This is one of the consequences of using inheritance. While you _can_ do it, I would caution against it. Here's some possible alternatives:

* Move the shared code you need into a new base class that both controllers inherit from **without** exposing any actions on it
* Move the shared code into a _collaborator_ that you create or inject into each controller
* Make **UploadFileStream** virtual so you can override it and apply `[MapToApiVersion("1.0")]`
* Refactor your implementation of **IDirectRouteProvider** to understand `[NonAction]`, `[Obsolete]`, or some other similar mechanism that would exclude it from inherited routes
* Extend `[MapToApiVersion]` or create your own attribute implementing **IApiVersionProvider** that supports inheritance
  * This will solve the routing problem because the action will never match by API version anymore, but you'll still have _bloat_ as you can _uninherit_ an action

I hope that helps. Let me know if you have more questions.

**Comment by dougbu** [comment] 2019-02-06 04:02
Thanks very much @commonsensesoftware. I much appreciate you jumping in here!

@angelacalborean thank you for your feedback. We're closing this issue as the questions asked here have been answered.

**Closed by dougbu** 2019-02-06 04:02 UTC
