### ISSUE TITLE
ASP.NET Api wrong `HttpContext.Current.Request.Browser.Browser` get chrome on edge

### ISSUE THREAD

**Issue by WeihanLi** [aspnet/AspNetWebStack#102] opened 2017-11-17 07:35 UTC
I use `HttpContext.Current.Request.Browser.Browser` to get browser name,but I get "chrome" on edge.

**Comment by dougbu** [comment] 2018-04-03 21:58
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

See http://www.davevoyles.com/2015/01/28/microsofts-spartan-browser-uses-chrome-ua-string/ for a description of why Edge reports itself as Chrome.

**Closed by dougbu** 2018-04-03 21:58 UTC
