### ISSUE TITLE
Microsoft.AspNet.WebAPI.Cors.EnableCors attribute omitting OPTIONS when methods:"*"

### ISSUE THREAD

**Issue by oOMEOo** [aspnet/AspNetWebStack#199] opened 2018-09-28 09:10 UTC
I recently experienced issues with the `EnableCors` attribute from the `Microsoft.AspNet.WebAPI.Cors` (v5.2.6) namespace on a WebAPI controller. The configuration was working for `Delete`, `Post` and `Get`, but failed with a preflight request (`OPTIONS`) for a `PUT` request. I had specified the `methods `parameter to `"*"` like the below:

`[EnableCors(origins: "http://localhost:8000", headers: "", methods: "")]`

I eventually figured out that the wildcard did not include all the methods, specifically the `OPTIONS` method, which was causing the omission of the Accept Origins response header. I eventually had to specify the methods like the below:

`[EnableCors(origins: "http://localhost:8000", headers: "*", methods: "PUT,OPTIONS,GET,POST,DELETE")]`

This resolved the issue. My understanding was that the wildcard as the 'methods' parameter would have included the `OPTIONS` method but it didn't. Please either resolve this or document the explicit exclusion?

On a separate note, I also had issues with the case sensitivity of the parameters in `methods`. Lowercase caused a whole lot of issues and unexpected behavior. Please either document the case sensitivity or disregard the case?

I could not find an official API for the Microsoft.# namespace either. The closest I could find was for System.Web.Http.Cors (https://docs.microsoft.com/en-us/previous-versions/aspnet/dn308848%28v%3dvs.118%29) which does not mention any of this. This was the API referenced on your Website, found on your package's info on NuGet. Please make it simpler to identify the appropriate API for the Microsoft.# namespace.

**Comment by dougbu** [comment] 2018-11-01 23:58
Please see https://docs.microsoft.com/en-us/previous-versions/aspnet/dn314675%28v%3dvs.118%29 for documentation of the APIs available in the `System.Web.Http.Cors` namespace. In particular, https://docs.microsoft.com/en-us/previous-versions/aspnet/dn308848%28v%3dvs.118%29 describes `[EnableCors]` and https://docs.microsoft.com/en-us/previous-versions/aspnet/dn314700(v%3dvs.118) its `Methods` property.

Separately, your first example uses the empty string and not `"*"`. Was that a typo in your snippet or your application? (The empty string disallows all methods.)

**Comment by dougbu** [comment] 2018-11-27 22:52
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-11-27 22:52 UTC
Labels: question
